### ISSUE TITLE
syntax error, expect {, actual ident, pos 0, fastjson-version 1.2.44 	at 

### ISSUE THREAD

**Issue by ithjz** [lihengming/spring-boot-api-project-seed#125]
by: com.alibaba.fastjson.JSONException: syntax error, expect {, actual ident, pos 0, fastjson-version 1.2.44
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:451) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1261) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_User.deserialze(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:267) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:654) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:365) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:333) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:296) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:402) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:484) ~[fastjson-1.2.44.jar:na]
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.readType(FastJsonHttpMessageConverter.java:204) ~[fastjson-1.2.44.jar:na]
	... 58 common frames omitted

**Comment by ithjz** [comment]
restful的user post创建一个用户,   restful里的api方式创建用户
