### ISSUE TITLE
分页不行？

### ISSUE THREAD

**Issue by zhangxuewen** [lihengming/spring-boot-api-project-seed#13]
2017-07-04 00:12:24.154 ERROR 14120 --- [nio-8080-exec-1] c.c.project.configurer.WebMvcConfigurer  : 接口 [/user/list] 出现异常，方法：com.company.project.web.UserController.list，异常摘要：null

java.lang.NullPointerException: null
	at com.company.project.web.UserController.list(UserController.java:50) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_131]

**Comment by lihengming** [comment]
分页参数 page和size传了吗？

**Comment by lihengming** [comment]
对于一些必填参数，其实应该在文档中声明为必填项进行约束，但是为了使调用者疏忽文档时也能得到提示，我优化了 Controller 模板，对一些必填参数添加了 ```@RequestParam``` 注解（该注解```required()```默认为 ```true```），如：
```java
@PostMapping("/delete")
public Result delete(@RequestParam Integer id)
```
优化了异常处理器，如果一些必填的参数没有填写，会在Result中做出提示，如：
```json
{
  "code": 400,
  "message": "Required Integer parameter 'id' is not present"
}
```
对于分页参数，添加了默认值，如果不添加page、size参数，默认查询所有，如：
```java
public Result list(@RequestParam(defaultValue = "0") Integer page, @RequestParam(defaultValue = "0") Integer size)
```
这依赖于分页插件的下列配置项
```
properties.setProperty("pageSizeZero", "true");//分页尺寸为0时查询所有纪录不再执行分页
properties.setProperty("reasonable", "true");//页码<=0 查询第一页，页码>=总页数查询最后一页
```
