### ISSUE TITLE
改变CodeGenerator.java的路径

### ISSUE THREAD

**Issue by zhongqishang** [lihengming/spring-boot-api-project-seed#35]
我把CodeGenerator.java 放到 src/main/java 里面之后，就不能执行了，放在src/test/java 下面就可以，这是为什么呢？

**Comment by lihengming** [comment]
为什么要放在src/main/java 呢..

**Comment by lihengming** [comment]
它依赖的模版资源 & 配置都是基于test目录的

**Comment by zhongqishang** [comment]
我是单独建了一个工具的工程，想把这个单独摘出来的。所以就放在src/main/java下面了

**Comment by lihengming** [comment]
它依赖的模版资源 & 配置都是基于test目录的，你把模板移动到 src/main/resource下应该就可以了
--

**Comment by lihengming** [comment]
这里
```java
    private static final String TEMPLATE_FILE_PATH = PROJECT_PATH + "/src/test/resources/generator/template";//模板位置
```

**Comment by zhongqishang** [comment]
我这个地方是 src/main/resource 模板文件也是在这个里面。

**Comment by zhongqishang** [comment]
具体问题是
`Exception in thread "main" java.lang.NoClassDefFoundError: freemarker/template/Configuration
	at com.glad.tools.generator.CodeGenerator1.getConfiguration(CodeGenerator1.java:202)
	at com.glad.tools.generator.CodeGenerator1.genService(CodeGenerator1.java:146)
	at com.glad.tools.generator.CodeGenerator1.genCode(CodeGenerator1.java:71)
	at com.glad.tools.generator.CodeGenerator1.main(CodeGenerator1.java:64)
Caused by: java.lang.ClassNotFoundException: freemarker.template.Configuration
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more
`
这个没变化的情况下，CodeGenerator.java 放在src/main/java 下面就会发生上面这样的问题。
好无厘头。。

**Comment by lihengming** [comment]
@zhongqishang Maven 依赖 ```scope```

**Comment by zhongqishang** [comment]
soga!

**Comment by zhongqishang** [comment]
好了。3q!
