### ISSUE TITLE
WebMvcConfigurer 类的configureMessageConverters方法； 我注释掉重写的方法，就可以使用了；我也不知道具体原因

### ISSUE THREAD

**Issue by fubiao** [lihengming/spring-boot-api-project-seed#41]
java.lang.ClassCastException: com.company.project.model.User cannot be cast to com.company.project.model.User
	at com.alibaba.fastjson.serializer.ASMSerializer_3_User.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:304) ~[fastjson-1.2.22.jar:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:282) ~[fastjson-1.2.22.jar:na]
	at com.alibaba.fastjson.serializer.ASMSerializer_2_PageInfo.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:304) ~[fastjson-1.2.22.jar:na]
	at com.alibaba.fastjson.serializer.ASMSerializer_1_Result.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275) ~[fastjson-1.2.22.jar:na]

**Comment by lihengming** [comment]
和configureMessageConverters应该没关系，你看看是不是这个问题引起的：#33

**Comment by fubiao** [comment]
不是这个问题 引起 的；
但是有个我搞不懂的问题
1、我克隆你的项目；增删改查都能运行；
2、但是我把你的src目录和pom文件复制到一个新的目录下使用后，就只有增删改能运行，查就报上面的错； 最后，我把你的项目所有文件复制新的项目下，增删改查都能运行；我确认，我的新目录，未添加任何功能文件，除了pom文件中定义的项目名字不一样，其它src目录和pom配置 都是复制粘贴的；来回试了3遍了；

**Comment by lihengming** [comment]
代码从新生成一遍试试

**Comment by fubiao** [comment]
我使用eclipse和idea，在2台电脑上，都是这种问题；只 复制 src目录和 pom.xml文件

**Comment by lihengming** [comment]
我刚才亲自试了下，重新创建一个文件夹，把原项目的 src目录及pom.xml复制过来，导入IDEA中，运行 访问list接口 没有出现该问题。实在不行你就把整个项目文件夹复制过去修改项目名称吧，效果是一样的。

**Comment by fubiao** [comment]
好的，谢谢
