### ISSUE TITLE
运行2个小时左右，就会崩掉。很奇怪 ：Invocation of destroy method 'close' failed on bean with name 'dataSource'

### ISSUE THREAD

**Issue by lck671** [lihengming/spring-boot-api-project-seed#54]
[       Thread-3] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7591083d: startup date [Sun Sep 17 17:07:50 CST 2017]; root of context hierarchy

[       Thread-3] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-09-17 19:19:20.197  INFO 24527 --- [       Thread-3] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans

 [       Thread-3] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method 'close' failed on bean with name 'dataSource': java.lang.NoClassDefFoundError: com/alibaba/druid/pool/PreparedStatementPool
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/apache/catalina/Lifecycle$SingleUse
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:240)
        at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:354)

**Comment by mrFranklin** [comment]
@lck671 请问找到原因了? 分享一下呗。

**Comment by lck671** [comment]
@mrFranklin 没有日志，各种找不到原因，换了传统的ssm
